import type { ThreeKingdomsCharacter } from './types';

/**
 * Static dataset of Three Kingdoms characters.
 * Stats based on the classic Koei 'Romance of the Three Kingdoms' game series.
 */
export const CHARACTERS: ThreeKingdomsCharacter[] = [
  /* ──────────── SHU (蜀漢 / Thục Hán) ──────────── */
  {
    id: 'liu-bei',
    name: { cn: '劉備', en: 'Liu Bei', vi: 'Lưu Bị' },
    kingdom: 'shu',
    stats: { might: 71, intelligence: 76, politics: 78, charisma: 99, leadership: 82 },
    weapon: 'Dual Swords (雌雄雙股劍)',
    hometown: 'Trác Quận, U Châu',
    bio: 'Founding ruler of Shu Han. A descendant of the Han imperial family, known for his benevolence and ability to attract talented followers.',
  },
  {
    id: 'guan-yu',
    name: { cn: '關羽', en: 'Guan Yu', vi: 'Quan Vũ' },
    kingdom: 'shu',
    stats: { might: 97, intelligence: 75, politics: 62, charisma: 93, leadership: 90 },
    weapon: 'Green Dragon Crescent Blade (青龍偃月刀)',
    hometown: 'Giải Lương, Hà Đông',
    bio: 'The God of War. Sworn brother of Liu Bei, he was known for his unwavering loyalty, martial prowess, and reading the Spring and Autumn Annals.',
  },
  {
    id: 'zhang-fei',
    name: { cn: '張飛', en: 'Zhang Fei', vi: 'Trương Phi' },
    kingdom: 'shu',
    stats: { might: 98, intelligence: 36, politics: 22, charisma: 48, leadership: 78 },
    weapon: 'Serpent Spear (丈八蛇矛)',
    hometown: 'Trác Quận, U Châu',
    bio: 'The fierce tiger. Sworn brother of Liu Bei, famous for single-handedly defending the bridge at Changban against Cao Cao\'s army.',
  },
  {
    id: 'zhuge-liang',
    name: { cn: '諸葛亮', en: 'Zhuge Liang', vi: 'Gia Cát Lượng' },
    kingdom: 'shu',
    stats: { might: 38, intelligence: 100, politics: 95, charisma: 92, leadership: 98 },
    weapon: 'Feather Fan (羽扇)',
    hometown: 'Dương Đô, Lang Nha',
    bio: 'The Sleeping Dragon (臥龍). The greatest strategist of the era, he served as Chancellor of Shu Han and masterminded countless victories.',
  },
  {
    id: 'zhao-yun',
    name: { cn: '趙雲', en: 'Zhao Yun', vi: 'Triệu Vân' },
    kingdom: 'shu',
    stats: { might: 96, intelligence: 76, politics: 65, charisma: 81, leadership: 87 },
    weapon: 'Dragon Gallant Spear (龍膽槍)',
    hometown: 'Chân Định, Thường Sơn',
    bio: 'The Silver Dragon. Legendary for rescuing Liu Bei\'s infant son at the Battle of Changban, charging through Cao Cao\'s army alone.',
  },
  {
    id: 'ma-chao',
    name: { cn: '馬超', en: 'Ma Chao', vi: 'Mã Siêu' },
    kingdom: 'shu',
    stats: { might: 97, intelligence: 47, politics: 33, charisma: 75, leadership: 82 },
    weapon: 'Spear of Vengeance (虎頭金槍)',
    hometown: 'Mậu Lăng, Phù Phong',
    bio: 'The Splendid Lancer. Son of Ma Teng, he once made Cao Cao flee so desperately that Cao Cao cut his own beard to disguise himself.',
  },
  {
    id: 'huang-zhong',
    name: { cn: '黃忠', en: 'Huang Zhong', vi: 'Hoàng Trung' },
    kingdom: 'shu',
    stats: { might: 92, intelligence: 52, politics: 38, charisma: 62, leadership: 72 },
    weapon: 'Bow & Saber (弓刀)',
    hometown: 'Nam Dương',
    bio: 'The aged warrior. Despite his age, he was among the fiercest fighters in Shu. Famous for slaying Xiahou Yuan at the Battle of Mount Dingjun.',
  },
  {
    id: 'pang-tong',
    name: { cn: '龐統', en: 'Pang Tong', vi: 'Bàng Thống' },
    kingdom: 'shu',
    stats: { might: 28, intelligence: 98, politics: 88, charisma: 57, leadership: 75 },
    weapon: 'Staff',
    hometown: 'Tương Dương, Kinh Châu',
    bio: 'The Young Phoenix (鳳雛). Alongside Zhuge Liang, he was one of the two greatest minds. He devised the chain strategy at Red Cliffs but died young at Luofeng Slope.',
  },
  {
    id: 'jiang-wei',
    name: { cn: '姜維', en: 'Jiang Wei', vi: 'Khương Duy' },
    kingdom: 'shu',
    stats: { might: 90, intelligence: 89, politics: 68, charisma: 72, leadership: 88 },
    weapon: 'Spear (長槍)',
    hometown: 'Ký Huyện, Thiên Thủy',
    bio: 'Zhuge Liang\'s chosen successor. Originally a Wei general, he was the last bastion defending Shu and led 11 Northern Expeditions.',
  },
  {
    id: 'wei-yan',
    name: { cn: '魏延', en: 'Wei Yan', vi: 'Ngụy Diên' },
    kingdom: 'shu',
    stats: { might: 90, intelligence: 62, politics: 38, charisma: 35, leadership: 78 },
    weapon: 'Saber (大刀)',
    hometown: 'Nghĩa Dương',
    bio: 'Fiercely brave but controversial. He served Shu with distinction but was killed after Zhuge Liang\'s death in a power struggle.',
  },

  /* ──────────── WEI (曹魏 / Tào Ngụy) ──────────── */
  {
    id: 'cao-cao',
    name: { cn: '曹操', en: 'Cao Cao', vi: 'Tào Tháo' },
    kingdom: 'wei',
    stats: { might: 72, intelligence: 91, politics: 96, charisma: 96, leadership: 99 },
    weapon: 'Sword of Heaven (倚天劍)',
    hometown: 'Tiêu Huyện, Bái Quốc',
    bio: 'The Hero of Chaos. Supreme warlord of the north, brilliant poet, strategist and statesman who laid the foundation for the Wei dynasty.',
  },
  {
    id: 'xiahou-dun',
    name: { cn: '夏侯惇', en: 'Xiahou Dun', vi: 'Hạ Hầu Đôn' },
    kingdom: 'wei',
    stats: { might: 90, intelligence: 52, politics: 48, charisma: 72, leadership: 80 },
    weapon: 'Crescent Blade (麒麟牙)',
    hometown: 'Tiêu Huyện, Bái Quốc',
    bio: 'Cao Cao\'s most loyal general. Famous for swallowing his own eye after it was shot out by an arrow — "Essence of my parents, I cannot discard it!"',
  },
  {
    id: 'xiahou-yuan',
    name: { cn: '夏侯淵', en: 'Xiahou Yuan', vi: 'Hạ Hầu Uyên' },
    kingdom: 'wei',
    stats: { might: 88, intelligence: 48, politics: 42, charisma: 55, leadership: 82 },
    weapon: 'Spear (長槍)',
    hometown: 'Tiêu Huyện, Bái Quốc',
    bio: 'Master of lightning warfare. Cousin of Cao Cao, he was famed for rapid maneuvers but fell to Huang Zhong at Mount Dingjun.',
  },
  {
    id: 'dian-wei',
    name: { cn: '典韋', en: 'Dian Wei', vi: 'Điển Vi' },
    kingdom: 'wei',
    stats: { might: 96, intelligence: 18, politics: 12, charisma: 48, leadership: 50 },
    weapon: 'Twin Halberds (雙鐵戟)',
    hometown: 'Kỷ Ngô, Trần Lưu',
    bio: 'The Evil Tiger. Cao Cao\'s personal bodyguard whose strength was compared to that of an ancient warrior. He died defending Cao Cao\'s retreat at Wan Castle.',
  },
  {
    id: 'xu-chu',
    name: { cn: '許褚', en: 'Xu Chu', vi: 'Hứa Chử' },
    kingdom: 'wei',
    stats: { might: 95, intelligence: 22, politics: 18, charisma: 42, leadership: 55 },
    weapon: 'Great Saber (大砍刀)',
    hometown: 'Tiều Huyện, Bái Quốc',
    bio: 'The Tiger Fool. Cao Cao\'s mighty bodyguard. Once fought Ma Chao to a standstill in a legendary duel where he stripped off his armor mid-combat.',
  },
  {
    id: 'zhang-liao',
    name: { cn: '張遼', en: 'Zhang Liao', vi: 'Trương Liêu' },
    kingdom: 'wei',
    stats: { might: 90, intelligence: 72, politics: 56, charisma: 68, leadership: 88 },
    weapon: 'Halberd (鉤鐮刀)',
    hometown: 'Mã Ấp, Nhạn Môn',
    bio: 'One of the Five Great Generals of Wei. He terrorized Wu at the Battle of Hefei, where 800 men routed Sun Quan\'s army of 100,000.',
  },
  {
    id: 'sima-yi',
    name: { cn: '司馬懿', en: 'Sima Yi', vi: 'Tư Mã Ý' },
    kingdom: 'wei',
    stats: { might: 48, intelligence: 97, politics: 94, charisma: 78, leadership: 92 },
    weapon: 'Feather Fan (羽扇)',
    hometown: 'Ôn Huyện, Hà Nội',
    bio: 'The Cunning Wolf. Zhuge Liang\'s greatest rival. His patience and cunning eventually led his descendants to overthrow Wei and found the Jin dynasty.',
  },
  {
    id: 'cao-ren',
    name: { cn: '曹仁', en: 'Cao Ren', vi: 'Tào Nhân' },
    kingdom: 'wei',
    stats: { might: 82, intelligence: 68, politics: 62, charisma: 52, leadership: 85 },
    weapon: 'Saber (大刀)',
    hometown: 'Tiêu Huyện, Bái Quốc',
    bio: 'The Unyielding Shield. Cao Cao\'s cousin and master defender who held the fortress of Fan Castle against overwhelming odds.',
  },
  {
    id: 'jia-xu',
    name: { cn: '賈詡', en: 'Jia Xu', vi: 'Giả Hử' },
    kingdom: 'wei',
    stats: { might: 25, intelligence: 96, politics: 88, charisma: 42, leadership: 62 },
    weapon: 'None (謀士)',
    hometown: 'Cô Tạng, Vũ Uy',
    bio: 'The Poisonous Strategist. Known as the most cunning advisor, his schemes once brought Cao Cao to the brink of death at Wan Castle.',
  },
  {
    id: 'guo-jia',
    name: { cn: '郭嘉', en: 'Guo Jia', vi: 'Quách Gia' },
    kingdom: 'wei',
    stats: { might: 15, intelligence: 98, politics: 80, charisma: 78, leadership: 65 },
    weapon: 'None (謀士)',
    hometown: 'Dương Địch, Dĩnh Xuyên',
    bio: 'Cao Cao\'s favorite advisor who died young. Cao Cao lamented: "If Guo Jia had lived, I would never have suffered at Red Cliffs."',
  },

  /* ──────────── WU (東吳 / Đông Ngô) ──────────── */
  {
    id: 'sun-ce',
    name: { cn: '孫策', en: 'Sun Ce', vi: 'Tôn Sách' },
    kingdom: 'wu',
    stats: { might: 92, intelligence: 71, politics: 62, charisma: 90, leadership: 88 },
    weapon: 'Spear (古錠刀)',
    hometown: 'Phú Xuân, Ngô Quận',
    bio: 'The Little Conqueror. Founded the Wu kingdom at the age of 17, conquering the Jiangdong region with charm and martial prowess.',
  },
  {
    id: 'sun-quan',
    name: { cn: '孫權', en: 'Sun Quan', vi: 'Tôn Quyền' },
    kingdom: 'wu',
    stats: { might: 62, intelligence: 78, politics: 88, charisma: 90, leadership: 85 },
    weapon: 'Sword (古鍛刀)',
    hometown: 'Phú Xuân, Ngô Quận',
    bio: 'Ruler of Wu. Consolidated the kingdom his father and brother built. Even Cao Cao said: "If I had a son like Sun Quan, that would be enough."',
  },
  {
    id: 'zhou-yu',
    name: { cn: '周瑜', en: 'Zhou Yu', vi: 'Chu Du' },
    kingdom: 'wu',
    stats: { might: 68, intelligence: 97, politics: 81, charisma: 90, leadership: 93 },
    weapon: 'Sword (古錠刀)',
    hometown: 'Thư Huyện, Lư Giang',
    bio: 'The handsome strategist. Mastermind behind the fire attack at the Battle of Red Cliffs that destroyed Cao Cao\'s fleet. Said with his dying breath: "Since heaven produced Zhou Yu, why did it also produce Zhuge Liang?"',
  },
  {
    id: 'lu-xun',
    name: { cn: '陸遜', en: 'Lu Xun', vi: 'Lục Tốn' },
    kingdom: 'wu',
    stats: { might: 55, intelligence: 95, politics: 85, charisma: 72, leadership: 90 },
    weapon: 'Sword (飛影劍)',
    hometown: 'Ngô Huyện, Ngô Quận',
    bio: 'The hidden genius. Destroyed Liu Bei\'s forces at the Battle of Yiling using fire tactics, proving himself one of the finest strategists of the era.',
  },
  {
    id: 'gan-ning',
    name: { cn: '甘寧', en: 'Gan Ning', vi: 'Cam Ninh' },
    kingdom: 'wu',
    stats: { might: 92, intelligence: 38, politics: 22, charisma: 55, leadership: 72 },
    weapon: 'Chain & Blade (鈴鐺刀)',
    hometown: 'Lâm Giang, Ba Quận',
    bio: 'The Bell Raider. A former pirate turned general of Wu, known for his fearless night raid on Cao Cao\'s camp with just 100 horsemen.',
  },
  {
    id: 'taishi-ci',
    name: { cn: '太史慈', en: 'Taishi Ci', vi: 'Thái Sử Từ' },
    kingdom: 'wu',
    stats: { might: 93, intelligence: 48, politics: 32, charisma: 62, leadership: 70 },
    weapon: 'Twin Rods (雙鐵鞭)',
    hometown: 'Hoàng Huyện, Đông Lai',
    bio: 'A warrior of supreme martial skill who famously dueled Sun Ce to a draw. Dying, he lamented: "A man should cut down all enemies — how can I die here?"',
  },
  {
    id: 'huang-gai',
    name: { cn: '黃蓋', en: 'Huang Gai', vi: 'Hoàng Cái' },
    kingdom: 'wu',
    stats: { might: 80, intelligence: 68, politics: 52, charisma: 65, leadership: 75 },
    weapon: 'Iron Whip (鐵鞭)',
    hometown: 'Tuyền Lăng, Linh Lăng',
    bio: 'Hero of Red Cliffs. His self-sacrifice gambit — accepting the "bitter torture" ruse — was key to the fire attack that burned Cao Cao\'s navy.',
  },
  {
    id: 'lu-meng',
    name: { cn: '呂蒙', en: 'Lu Meng', vi: 'Lữ Mông' },
    kingdom: 'wu',
    stats: { might: 78, intelligence: 82, politics: 72, charisma: 68, leadership: 80 },
    weapon: 'Halberd (方天畫戟)',
    hometown: 'Phú Bi, Nhữ Nam',
    bio: 'From a rough warrior to a brilliant strategist. He captured Jingzhou and brought about Guan Yu\'s downfall — the source of the saying "Look at Lu Meng with new eyes."',
  },

  /* ──────────── OTHER (群雄 / Quần hùng) ──────────── */
  {
    id: 'lu-bu',
    name: { cn: '呂布', en: 'Lü Bu', vi: 'Lữ Bố' },
    kingdom: 'other',
    stats: { might: 100, intelligence: 32, politics: 18, charisma: 30, leadership: 45 },
    weapon: 'Sky Piercer Halberd (方天畫戟)',
    hometown: 'Cửu Nguyên, Ngũ Nguyên',
    bio: 'The mightiest warrior of the age. "Among men, Lü Bu; among horses, Red Hare." He was unbeatable in combat but repeatedly betrayed his lords.',
  },
  {
    id: 'dong-zhuo',
    name: { cn: '董卓', en: 'Dong Zhuo', vi: 'Đổng Trác' },
    kingdom: 'other',
    stats: { might: 78, intelligence: 42, politics: 38, charisma: 18, leadership: 60 },
    weapon: 'Sword (七星寶刀)',
    hometown: 'Lâm Thao, Lũng Tây',
    bio: 'The tyrant who seized control of the Han court. His brutal reign ignited the chaos of the Three Kingdoms as warlords united to oppose him.',
  },
  {
    id: 'yuan-shao',
    name: { cn: '袁紹', en: 'Yuan Shao', vi: 'Viên Thiệu' },
    kingdom: 'other',
    stats: { might: 55, intelligence: 65, politics: 72, charisma: 78, leadership: 68 },
    weapon: 'Sword',
    hometown: 'Nhữ Dương, Nhữ Nam',
    bio: 'Lord of the north. Despite commanding the largest army, his indecisiveness led to his crushing defeat by Cao Cao at the Battle of Guandu.',
  },
  {
    id: 'diao-chan',
    name: { cn: '貂蟬', en: 'Diao Chan', vi: 'Điêu Thuyền' },
    kingdom: 'other',
    stats: { might: 30, intelligence: 75, politics: 72, charisma: 98, leadership: 25 },
    weapon: 'Twin Maces (雙鋼鞭)',
    hometown: 'Mộc Nhĩ, Tịnh Châu',
    bio: 'One of the Four Beauties of ancient China. She used her beauty strategically to drive a wedge between Dong Zhuo and Lü Bu, changing history.',
  },
  {
    id: 'hua-tuo',
    name: { cn: '華佗', en: 'Hua Tuo', vi: 'Hoa Đà' },
    kingdom: 'other',
    stats: { might: 15, intelligence: 88, politics: 55, charisma: 85, leadership: 15 },
    weapon: 'Surgical Tools (手術刀)',
    hometown: 'Tiêu Huyện, Bái Quốc',
    bio: 'The legendary physician. He invented anesthesia ("Mafeisan") and offered to perform brain surgery on Cao Cao — who executed him out of suspicion.',
  },
  {
    id: 'zhang-jiao',
    name: { cn: '張角', en: 'Zhang Jiao', vi: 'Trương Giác' },
    kingdom: 'other',
    stats: { might: 35, intelligence: 78, politics: 62, charisma: 88, leadership: 72 },
    weapon: 'Taoist Staff (太平道杖)',
    hometown: 'Cự Lộc, Ký Châu',
    bio: 'Leader of the Yellow Turban Rebellion. His cry "The Blue Heaven has perished, the Yellow Heaven shall rise!" triggered the collapse of the Han dynasty.',
  },
  {
    id: 'sun-jian',
    name: { cn: '孫堅', en: 'Sun Jian', vi: 'Tôn Kiên' },
    kingdom: 'other',
    stats: { might: 90, intelligence: 62, politics: 55, charisma: 80, leadership: 82 },
    weapon: 'Ancient Forged Saber (古錠刀)',
    hometown: 'Phú Xuân, Ngô Quận',
    bio: 'The Tiger of Jiangdong. Father of Sun Ce and Sun Quan, he was the first to breach Dong Zhuo\'s capital and discovered the Imperial Seal.',
  },
  {
    id: 'yan-liang',
    name: { cn: '顏良', en: 'Yan Liang', vi: 'Nhan Lương' },
    kingdom: 'other',
    stats: { might: 90, intelligence: 35, politics: 28, charisma: 42, leadership: 62 },
    weapon: 'Great Saber (大砍刀)',
    hometown: 'Ký Châu',
    bio: 'Top general of Yuan Shao. Despite his fearsome strength, he was slain by Guan Yu in a single charge at the Battle of Boma.',
  },
  {
    id: 'wen-chou',
    name: { cn: '文醜', en: 'Wen Chou', vi: 'Văn Xú' },
    kingdom: 'other',
    stats: { might: 88, intelligence: 30, politics: 25, charisma: 38, leadership: 58 },
    weapon: 'Spear (長槍)',
    hometown: 'Ký Châu',
    bio: 'Yuan Shao\'s other top general. Paired with Yan Liang as a deadly duo, he too fell in combat during Yuan Shao\'s war against Cao Cao.',
  },
  {
    id: 'pang-de',
    name: { cn: '龐德', en: 'Pang De', vi: 'Bàng Đức' },
    kingdom: 'other',
    stats: { might: 92, intelligence: 48, politics: 30, charisma: 52, leadership: 68 },
    weapon: 'Great Saber (大砍刀)',
    hometown: 'Nam An, Vũ Đô',
    bio: 'The White Knight. He carried his own coffin to battle against Guan Yu, showing his resolve. Though captured, he refused to surrender and was executed.',
  },
];
